### ISSUE TITLE
Ideas for new_shared_index_map

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#2]
1. Don't define a destructor, if you don't have to. (By defining a destructor you disable move semantics. See [this](https://en.cppreference.com/w/cpp/language/rule_of_three) - Rule of five: "Because the presence of a user-defined destructor [...] prevents implicit definition of the move constructor and the move assignment operator [...]")

2. Element::operator[] and Element::at() - You may want to think about switching these around. The STL convention at least seems to be, that 'at' performs a check to see if the element exists, 'operator[]' doesn't (std::vector does it this way for example).

3. Use references when possible, instead of pointers. For Example 'SharedIndexMap::Element::db_'
line 84: 'SharedIndexMap<T>*' -> 'SharedIndexMap<T>&'

4. Probably works without this as well, but just to be completely standard conform you could define a few more things in the Iterarators: 'difference_type', 'reference' and 'pointer'. Also defining a 'swap()' function and an overload for 'operator->' might not be a bad idea. Generally everything described [here](https://en.cppreference.com/w/cpp/named_req/InputIterator) and [here](https://en.cppreference.com/w/cpp/named_req/Iterator) (Although the links may be a bit hard to read)

**Comment by philsegeler** [comment]
1. Already done. I don't think a custom destructor is necessary at all anywhere, since everything works with shared pointers.

2. There is a problem with that suggestion. The *SharedIndexMap* is **not** supposed to function like an ```std::vector```, but similar to an ```std::map``` and should also  be 100% thread-safe. Element indices (keys)  should **NEVER** change for a specific element. And it should **NEVER** under **ANY** circumstances cause a segfault. The ```at()``` is supposed to throw an exception if it cannot find an element key inside the internal ```std::map```, while the ```[]``` operator can just return an Element with a ```nullptr``` shared pointer and one should check with ```elem.is_valid()``` to see if the element exists or not. This is unlike ```std::map```'s ```[]``` operator which creates the element in that case. Elements can only be created with ```append``` or ```extend```.

3. I don't know if this is possible, since the pointers are **inside** the classes of the *SharedIndexMap* themselves and it might cause recursive errors, but i will try.

4.  Yes, it works without them, so i do not know if they could be of any use. The iterators are only supposed to be read-only, so an input iterator suffices. One should be able to change the elements through the shared pointer ```elem.p_``` but not the pointer itself. If one wants to change the pointer one should use ```force_append``` (to be implemented).

5. All iterators are only supposed to be used inside the ```renderer->updateData()``` and physics engine ```updateMultiThread()```, because i do not think i can make them really thread-safe, when new elements are added asynchronously. A user usually wants direct access, if they created an object on the fly. This is why ```append``` just appends to ```pending_*``` maps, which are then synchronized at the end of each frame. The user API will synchronize directly, but internally we will not.

6. I am thinking about possibly adding a reference count (some elements like materials/textures/TextureCombineModes need it, because they can be shared by multiple meshes). You said you had other ideas regarding it in the future (?). I will make this the current design, but it can of course be changed in the future. 

7. Using a ```std::set``` and allocating memory every frame is probably very inefficient, so a custom container can be used inside ```Changed``` and ```Deleted``` instead, which might be more efficient. I won't implement it myself as i probably told you before, but I will add it as a possible enhancement.

8. A solution must be found inside the interpreter for linked materials/scenes etc. which cannot be found directly inside the .csl, but could already be loaded from elsewhere. An idea would be to just check the main *SharedIndexMap* every time. I will implement a ```count```, which can be used for this purpose.

**Comment by philsegeler** [comment]
UPDATE:

Finalized the new ```OE_SharedIndexMap``` implementation. It is not particularly fast, but it is functional.

(1.) I need the destructor due to the destructor of the base class ```OE_THREAD_SAFETY_OBJECT``` being ```virtual```. One will never need to copy the ```OE_SharedIndexMap```s either way i think. They will be global and visible to all and can be passed by reference if needed (for example in the interpreter). The copy constructor has been deleted explicitly. It wouldn't function correctly by default anyways, since for some reason ```std::*map``` likes to move objects around instead of deep-copying, which causes double free errors.

(3.) Adding references is indeed possible in ```Changed``` and ```Deleted``` but not in ```Element```. By the way ```force_append``` has now been implemented. ```force_append_now``` and ```append_now``` have also been implemented to add elements and make them directly visible from the user API. ```*_now``` is also used by the interpreter internally to ensure correct element references. ```extend``` will remain asynchronous-only though, because for the time being no ```extend_now``` is needed.

(6.) Reference counting will be implemented in the future.

(8.) ```count``` and ```is_pending``` are now implemented both for indices and names.

(9.) ```OE_THREAD_SAFETY_OBJECT``` finally has proper constructor, copy constructor, move constructor, copy assignment operator and destructor!! This particular class hadn't been updated otherwise since 2016.
