### ISSUE TITLE
Obj file parser

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#23]
Do we actually even really need our own file format?

Is there any additional information we put inside the *.csl files, or could we theoretically just write an *.obj parser and not have to use a custom blender plugin?

**Comment by philsegeler** [comment]
Yes we really *do* need our own file format.

1. ```.obj``` is a generic format that supports many things we do not support (for example quads instead of only triangles like ```.csl```. Quads and NGons are made into triangles inside the Blender exporter automatically) Do you want to handle all of that inside the Interpreter with much higher performance requirements as well?

2. We would not have flexibility in how we store scenes, materials, shaders and textures.

3. How would we store [animations](https://stackoverflow.com/questions/757145/do-wavefront-obj-files-support-animation)  and rigging.., or properties for the physics engine..., or ```.obj``` files linking to other ```.obj``` files to make open-world loading straightforward for example? I could list more but this is just off the top of my head. Or even packing textures inside the ```.csl```. The possibilities are endless with our own format.

4. One would have to translate all the different ```.obj``` types to our own engine structure anyways, so why not do it through Blender and let Blender handle all the complexity of different file formats and have the exporter work for all of them? I have successfully imported a random ```.obj``` model from the internet into Blender and after a few adjustments of materials exported it to ```.csl``` and displayed it correctly in the renderer. Its name is ```some_car.csl``` and can be found in the assets.

5. Every game engine has its own format and for good reason, why not we? :) The closest to a generic 3D game engine format would be [COLLADA](https://www.khronos.org/collada/), but we would still lose flexibility and functionality and we cannot expect to support everything in COLLADA. Blender can still import COLLADA.

6. Assuming we adopted for example ```COLLADA```, which would in theory be a better fit. What would we do with ```.obj``` files? Import them into Blender, export them into ```COLLADA``` and interpret them into our own structure? Adopt the ```COLLADA``` structure? Write *yet another* interpreter for ```.obj```? For ```.fbx``` as well?

7. Blender supports custom object properties. We could use those to store various parameters (for example physics, storage or open-world related)  and have them picked up by the exporter.

8. You could still make a limited direct ```.obj``` to ```.csl``` translator if you like, but i personally would not consider that high priority.

9. Compressed binary format when/how?

Summary: It is IMHO much simpler to write ONE exporter and ONE fast parser and interpreter for a flexible file format suited to our engine capabilities than limiting ourselves to any specific generic asset format. We would need to convert to our internal format anyways unless we completely rewrite everything yet again.

Do you need any more arguments or are these enough?

**Comment by antsouchlos** [comment]
Ok ok, I get it. No obj parser :D
