### ISSUE TITLE
Plug for C++20 :P

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#25]
Based on one part of issue #24 

We could actually implement the compile-time configuration similarly to one of the proposals in the aforementioned issue, namely

```C++
constexpr oe::const_string_t conf = "{"
                                    "    'option1': true,"
                                    "    'option2': true,"
                                    "    'list_option3': {"
                                    "        'inside_opt1': true,"
                                    "        'inside_opt2': false"
                                    "    }"
                                    "}";


int main() {
    oe::preconfigure<conf>();

    oe::init("Oxygen Engine Demo", 1280, 720);
    oe::load_world_func("some_file.csl");
    oe::start();

    return 0;
}
```

This would require somewhat refactoring the structure of the internal API, as well as the use of C++20 for non-type-template-parameters.

Below is an example implementation. The basic idea is the following:

We create a completely object oriented API for the engine. There is one class, `oxygen_engine_t`, that does absolutely
everything. The C-Style API is a wrapper around that: A single global variable, and each public API function simply calls the
corresponding `oxygen_engine_t` member function.

The necessity for a single top level class that handles everything arises because of the desire for compile-time configuration.
The JSON string is parsed at compile time, and the resulting configuration struct is used as a template parameter while defining
the global `oxygen_engine_t` instance. That way, one an `oxygen_engine_t` member function is called, all of the configuration
options are known beforehand.

The catch is that this actually requires `C++20` in order to be able to pass around the config string as a compile time constant.

https://godbolt.org/z/5q99a6qx8

**Comment by philsegeler** [comment]
Nice piece of code demonstration!

With your suggestion we have a serious problem because one would need to add an API function/method in 3(!) different places plus the implementation could only be in the .h and it would be a chore and a really large file. The 2016 version had a ```FEngine``` AND a ```FTaskmanager``` class and i though it would be simple to just have ONE task manager class in the end and the C-style API around it as a wrapper.

It could be possible to use this in your own APIs internally if you want (```csl``` for example) if you manage to find a use case. You could change the interpreter class for example to work with templates like this. The only requirement by me would be to be C++17 compatible in the end with the same API. (This means only ```csl::interpret``` should stay the same. The class doesn't have to etc.) But you said you have not found a use case yet, so idk.

I think in any case the drawbacks outweigh the benefits for the main API in the end and as you said we still cannot find a use case for user-configurable compile-time constants.

Can you use the templated constructor with C++17 even if it is not a compile-time constant in the end?

**Comment by antsouchlos** [comment]
Now that you say it, having to put every implementation in the header file is kind of a dealbreaker in this case, I agree :D

In order to be able to properly pass around the config options we would have to use C++20 for non-type-template-arguments.

Otherwise this

```C++
template<const_config_t Conf>
class oxygen_engine_t : public oxygen_engine_base_t {
    // ...
};
```

becomes this


```C++
template<bool ConfOption1_, bool ConfOption2_ /* ... */>
class oxygen_engine_t : public oxygen_engine_base_t {
    // ...
};
```

and we would only be able to pass integer and boolean types as config options (And enums, but they essentially are integer types).

And I am not entirely sure what you are refering to when you say "templated constructor" in your last sentence.

**Comment by philsegeler** [comment]
Ok, I thought it worked with C++17 only with making those parameters not ```constexpr``` but i was wrong.

So we cannot use this :D

If you found a use case where you really really really want to use user-configurable compile-time parameters on the main API bug me again and reopen this. But remember this is a game engine and almost everything should be able to change at start time or runtime whenever possible!
