### ISSUE TITLE
Changing the directory structure

### ISSUE THREAD

**Issue by antsouchlos** [antsouchlos/OxygenEngine2#6]
Another change I would propose, while we are in the process of setting the conventions for everything, is changing the directory structure.
There are a few things I don't particularly like, e.g. The plethora of `*.cpp` files in the root directory of the repo.

# Proposed changes

## Examples directory

Create an `examples` folder and move everything related to examples and demos in there

## File prefixes

I would propose removing all the `OE_`, `CSL_`, `NRE_`, etc. prefixes from header and source filenames.

All `CSL` files are in a `Carbon` folder; All `NRE` files are in a `Renderer` folder, etc. It is not necessary to prefix the filenames in order to understand what part of the project every file belongs to. This is built into the directory structure:

```c++
#include <Carbon/Exceptions.h>
#include <Renderer/Renderer_Main.h>
// ...
```

## `include` directory

Create an `OxygenEngine` folder inside the `include` directory and move everything in there. While this may seem stupid at first, it has the effect of changing the includes as shown below:
```c++
#include <OxygenEngine/Carbon/...>
```

This is benefitial for actual game code using the game engine, as it is clear which part of the code belongs to the game itself and which to the engine,

## Libraries

Include the libraries as submodules instead of having library sourcecode in this repo. Or better yet, configure meson to automatically deownload dependencies where possible.

## Hydrogen Engine

Maybe create an entirely new repo for the physics engine and include it with a submodule.

## Compilation configuration files

If possible, create a folder with a name along the lines of `build_conf` and move all files related to build configuration (or as much as possible anyway) in there, to clean up the root directory a bit,

**Comment by philsegeler** [comment]
## Examples directory

This is not a bad idea. This means we should restructure a bit though. Currently `meson` builds OE as a static library and then links it to whatever other .cpp files one has. This means we should then build OE as a dynamic library (.so) and structure it as a dependency. Then one could use our header files and the `.so` theoretically.

## File prefixes

Oh no no no. This has the following problem. First there might be multiple files with the same name. This is confusing since when editing i only see filenames and NOT the whole directory (too much space). I **need** unique file names to differentiate between them. I can consider making them all lower case and the directories clear names (such as `csl` instead of `Carbon`, `nre` instead of `Renderer`, `nre_gpu_api.h` instead of `NRE_GPU_API.h`, `csl_interpreter.h` instead of `CSL_Interpreter.h`

Also there might be a problem with some build systems and same file names (e.g. android)

## `include` directory

Not a bad idea but make it plain `oe`, like : `include/oe/csl/csl_interpreter.h` and alko for the `src` like  `src/oe/csl/csl_interpreter.cpp`

## Libraries

Yes

## Hydrogen Engine

Implement ***something*** for the physics engine, integrate it inside the main engine and then we **might** start talking about that. :)

## Compilation configuration files

I don't think it is necessary. Some things make sense to exist in the main directory. Let's remove source files or log files or `.csl` files (i've already cleaned them up in an `assets` directory, but we can dump them in `examples` as you said), but not `meson.build` and co. Meson automatically creates a `builddir` directory so no build artifacts if you just put that directory into `.gitignore`.

**Comment by philsegeler** [comment]
Also i think meson expects `meson.build` to be in a top level directory but i am not sure.

**Comment by antsouchlos** [comment]
## Examples directory

Building as a dynamic library is a good idea.

## `include` directory

Plain `oe` sounds good.

## Hydrogen Engine

Valid point.

## Compilation configuration files

Let's leave the compilation conf files where they are for now then.

## File prefixes

This is the only thing I really disagree with.

First of all I am not entirely sure what you mean by problems with same file names for other build systems. That would be a very bad build system, if all filenames had to be unique.

Secondly, which filenames even are the same? On a very shallow look-through I did not find any filenames that would be the same without the prefixes.

Thirdly, for filenames that would be the same without prefixes, there is a strong argument to be had about combining the contents into a single file and making them available globally.

The one thing we can already agree about is making everything lowercase and renaming the include directory folder names.

**Comment by philsegeler** [comment]
## File prefixes

Some examples of files with same name:

`oe_api.h` => `api.h`

`nre_gpu_api.h`    => `api.h`

`nre_gl3_api.h`     => `api.h`

`nre_gles2_api.h` => `api.h`

More

`nre_gpu_shaders.h`    => `shaders.h`

`nre_gl3_shaders.h`     => `shaders.h`

`nre_gles2_shaders.h` => `shaders.h`

`nre_vulkan_shaders.h`(future)

`nre_renderer_shaders.h` (future)

Same for equivalent `.cpp` files.

More:

`csl_exceptions.h`  => `exceptions.h`
`oe_error.h`  => `exceptions.h`
`nre_exceptions.h` => `exceptions.h`

It would especially make working with the renderer a nightmare.

**Comment by philsegeler** [comment]
And if i decide to split the api files even more (which might happen considering `NRE_GL3_API.cpp` is 1448 lines long right now, then even worse

**Comment by philsegeler** [comment]
Combining all those `api.h` in one would make the `api.h` and the equivalent `.cpp` files 10k lines long or something in the end. Combining files is not a realistic solution not even for the exceptions and definitely not for the shaders.

**Comment by antsouchlos** [comment]
While I am not entirely happy doing it and think there must be a better way to differentiate between the files while developing, I will settle for renaming the files to lowecase and changing the include directory folder names.

I will bug you again about the topic of filename prefixes at some point in the future though.
Marking this issue as closed.

**Comment by philsegeler** [comment]
## File prefixes

Another idea i had is the following that would be possible for all files which would otherwise have the same name.

`oe_api.h` => `api_oe.h`

`nre_gpu_api.h`    => `api_gpu.h`

`nre_gl3_api.h`     => `api_gl3.h`

`nre_gles2_api.h` => `api_gles2.h`

More

`nre_gpu_shaders.h`    => `shaders_gpu.h`

`nre_gl3_shaders.h`     => `shaders_gl3.h`

`nre_gles2_shaders.h` => `shaders_gles2.h`

`nre_vulkan_shaders.h`(future)

`nre_renderer_shaders.h` (future)

Same for equivalent `.cpp` files.

More:

`csl_exceptions.h`  => `exceptions_csl.h`
`oe_error.h`  => `exceptions_oe.h`
`nre_exceptions.h` => `exceptions_nre.h`

For everything else, the prefixes could be removed.

**Comment by antsouchlos** [comment]
That I could live with. Will close the issue once renaming has finished.

**Comment by philsegeler** [comment]
Yeah actually this is a good idea for all those issues, Reoprn them, then only close them, when the renaming/restructuring has finished.
